# Generated by Django 4.2.7 on 2024-03-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='ramo',
            new_name='ramo_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
